export const foodKeywords = [
  "food",
  "diet",
  "eat",
  "eating",
  "kaon",
  "pagkaon",
  "pagkain",
  "meal",
  "meals",
  "nutrition",
  "nutritional",
  "carbohydrate",
  "carbohydrates",
  "sugar",
  "sweet",
  "sweetened",
  "rice",
  "bread",
  "fruit",
  "fruits",
  "vegetable",
  "vegetables",
  "protein",
  "fat",
  "fats",
  "snack",
  "snacks",
  "drink",
  "drinks",
  "beverage",
  "beverages",
  "menu",
  "dish",
  "dishes",
  "cuisine",
  "calorie",
  "calories",
  "fiber",
  "glycemic",
  "index",
  "portion",
  "serving",
  "servings",
  "kadamuan",
  "kadamuon",
  "consume",
  "consumption",
  "restriction",
  "restricted",
  "forbidden",
];

export const healthKeywordPatterns = [
  "diabetes",
  "hypertension",
  "high blood pressure",
  "blood pressure",
  "bp",
  "blood sugar",
  "glucose",
  "insulin",
  "hypoglycemia",
  "hyperglycemia",
  "hypertensive",
];

export const diabetesKeywordPatterns = [
  "diabetes",
  "diabetic",
  "blood sugar",
  "glucose",
  "insulin",
  "hypoglycemia",
  "hyperglycemia",
  "sugar",
];

export const hypertensionKeywordPatterns = [
  "hypertension",
  "high blood pressure",
  "blood pressure",
  "hypertensive",
  "bp",
  "highblood",
  "high blood",
];

export const mentionsKeyword = (
  message: string,
  keywords: string[],
): boolean => {
  const normalized = message.toLowerCase();
  return keywords.some((keyword) => normalized.includes(keyword));
};
